# -*- coding: utf-8 -*-
"""Lab2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WG77h8zAkpACl5b2MdYIcAe0QQal0a-1
"""

#create list with 10 integers
my_list = [10,2,3,4,5,6,8,4,3,6,7]
print(my_list)
#sum
print('sum',sum(my_list))
#max
print('max',max(my_list))
#min
print('min',min(my_list))
#Add element
my_list.append(81)
my_list.append(82)
#Remove element
my_list.remove(7)
print(my_list)
#reverse list
my_list.reverse()
print(my_list)
#sort-list
my_list.sort()
print(my_list)
#reverse-list
my_list.reverse()
print(my_list)


#Tuple
print('Tupple:')
fruits = ("apple", "banana", "cherry", "orange")
print(fruits)
print('second elemet:',fruits[1])
print('Last elemet:',fruits[3])

#tuples are immutable so we have to change tuples into list first
fruits = ['apple', 'banana', 'grape', 'melon']  # Example list
fruit_list = list(fruits)
fruit_list[2] = 'orange'
print('modified list:', fruit_list)

#union ,intersection and diffrence
# Define two sets
A = {1, 2, 3}
B = {3, 4, 5}

# Union: elements in A or B or both
union = A.union(B)
print("Union:", union)

# Intersection: elements common to both A and B
intersection = A.intersection(B)
print("Intersection:", intersection)
# Difference: elements in A but not in B
difference = A.difference(B)
print("Difference (A - B):", difference)

#Dictionary
students = {'Ali' :85,'Sara':90 ,'Abbas':95 }

#print keys and values
print('keys:',students.keys())
print('values:',students.values())