# -*- coding: utf-8 -*-
"""Resultreproduced.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tPRWkg745JiIbiU05_ULU1S8ddVNWAY8
"""

import numpy as np

# Create 1D array with length 20 for easier reshaping and operations
arr = np.arange(2, 22)
print('1D Array:', arr)

# Reshape to 4x5 matrix (total 20 elements)
matrix = arr.reshape(4, 5)
print('4x5 Matrix:\n', matrix)

# Mean, Median, Std
print('Mean:', np.mean(arr))
print('Median:', np.median(arr))
print('Standard Deviation:', np.std(arr))

# Create arr2 with same length for element-wise operations
arr2 = np.arange(11, 31)
print('Addition:', arr + arr2)
print('Multiplication:', arr * arr2)


#Matlablib

import matplotlib.pyplot as plt

# Line Plot
x = list(range(1, 11))
y = [i**2 for i in x]
plt.plot(x, y)
plt.title('Numbers vs Squares')
plt.xlabel('Numbers')
plt.ylabel('Squares')
plt.show()

# Bar Chart
students = ['Bilawal', 'Abas', 'Ahmed', 'Zara', 'Omar']
marks = [75, 30, 99, 12, 48]
plt.bar(students, marks)
plt.title('Student Marks')
plt.xlabel('Students')
plt.ylabel('Marks')
plt.show()

# Pie Chart
categories = ['Category A', 'Category B', 'Category C']
values = [40, 30, 30]
plt.pie(values, labels=categories, autopct='%1.1f%%')
plt.title('Category Distribution')
plt.show()